name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release Project
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5

      - name: Use Node.js ⬢
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false

      - name: Install dependencies 📦
        run: |
          corepack enable
          corepack prepare --activate
          pnpm install --frozen-lockfile

      - name: Test 🧪
        run: pnpm test

      - name: Build 🏗
        run: pnpm build

      - name: Publish 🚀
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
